### ISSUE TITLE
L'installation a échoué

### ISSUE THREAD

**Issue by nicolasVr** [YunoHost-Apps/mailman_ynh#11]
Sur un serveur à jour :

args:
  app: mailman
  args: domain=xxxxxx.ovh&path=%2Fmailman&admin_password=XXXXXXXXXX language=fr&is_public=1
  force: false
  label: Mailman
  no_remove_on_failure: false
ended_at: 2019-09-23 12:58:22.147896
env:
  YNH_APP_ARG_ADMIN_PASSWORD: '**********'
  YNH_APP_ARG_DOMAIN: xxxxx.ovh
  YNH_APP_ARG_IS_PUBLIC: 1
  YNH_APP_ARG_LANGUAGE: fr
  YNH_APP_ARG_PATH: /mailman
  YNH_APP_ID: mailman
  YNH_APP_INSTANCE_NAME: mailman
  YNH_APP_INSTANCE_NUMBER: '1'
  YNH_CWD: /var/cache/yunohost/from_file/mailman_ynh-1240761bf871657f82851bb5ef2da4d1a508d28a/scripts
  YNH_INTERFACE: api
  YNH_STDINFO: /tmp/tmprgf8RZ/stdinfo
  YNH_STDRETURN: /tmp/tmp5q6vdy/stdreturn
error: 'Une erreur inattendue est survenue : shell command return code: 1'
operation: app_install
related_to:
- - app
  - mailman
started_at: 2019-09-23 12:58:00.220380
success: false

**Comment by alexAubin** [comment]
Hmmm et il n'y a rien d'autre comme logs, tu es sur ?

**Comment by nicolasVr** [comment]
Si mais je ne suis pas certain qu'il soit prudent de les mettre en ligne, je peux les envoyer en privé ?

**Comment by alexAubin** [comment]
Hmmmoui si tu veux vraiment tu peux les poster genre sur https://framabin.org et m'envoyer le lien par email à alex.aubin [at] mailoo .org

**Comment by nicolasVr** [comment]
c'est fait

**Comment by alexAubin** [comment]
Le probleme viens de : 

```
2019-09-23 15:10:15,123: DEBUG - Unpacking mailman (1:2.1.23-1+deb9u4) ...
2019-09-23 15:10:19,861: DEBUG - Processing triggers for systemd (232-25+deb9u12) ...
2019-09-23 15:10:19,962: DEBUG - Processing triggers for man-db (2.7.6.1-2) ...
2019-09-23 15:10:20,062: DEBUG - Setting up mailman (1:2.1.23-1+deb9u4) ...
2019-09-23 15:10:20,163: DEBUG - locale: Cannot set LC_CTYPE to default locale: No such file or directory
2019-09-23 15:10:20,163: DEBUG - locale: Cannot set LC_MESSAGES to default locale: No such file or directory
2019-09-23 15:10:20,163: DEBUG - locale: Cannot set LC_ALL to default locale: No such file or directory
2019-09-23 15:10:20,364: DEBUG - Looking for enabled languages (this may take some time) ... done.
2019-09-23 15:10:25,076: DEBUG - Installing site language en ............................................. done.
2019-09-23 15:10:25,280: DEBUG - Configuring mailman for domain localhost.localdomain ...
2019-09-23 15:10:25,700: DEBUG - Traceback (most recent call last):
2019-09-23 15:10:25,700: DEBUG -   File "/usr/lib/mailman/bin/update", line 51, in <module>
2019-09-23 15:10:25,701: DEBUG -     from Mailman import MailList
2019-09-23 15:10:25,701: DEBUG -   File "/var/lib/mailman/Mailman/MailList.py", line 51, in <module>
2019-09-23 15:10:25,701: DEBUG -     from Mailman.Archiver import Archiver
2019-09-23 15:10:25,701: DEBUG -   File "/var/lib/mailman/Mailman/Archiver/__init__.py", line 17, in <module>
2019-09-23 15:10:25,701: DEBUG -     from Archiver import *
2019-09-23 15:10:25,701: DEBUG -   File "/var/lib/mailman/Mailman/Archiver/Archiver.py", line 37, in <module>
2019-09-23 15:10:25,701: DEBUG -     from Mailman.i18n import _
2019-09-23 15:10:25,701: DEBUG -   File "/var/lib/mailman/Mailman/i18n.py", line 37, in <module>
2019-09-23 15:10:25,701: DEBUG -     _ctype_charset = _get_ctype_charset()
2019-09-23 15:10:25,701: DEBUG -   File "/var/lib/mailman/Mailman/i18n.py", line 31, in _get_ctype_charset
2019-09-23 15:10:25,702: DEBUG -     old = locale.setlocale(locale.LC_CTYPE, '')
2019-09-23 15:10:25,702: DEBUG -   File "/usr/lib/python2.7/locale.py", line 581, in setlocale
2019-09-23 15:10:25,702: DEBUG -     return _setlocale(category, locale)
2019-09-23 15:10:25,702: DEBUG - locale.Error: unsupported locale setting
2019-09-23 15:10:25,902: DEBUG - dpkg: error processing package mailman (--configure):
2019-09-23 15:10:25,903: DEBUG -  subprocess installed post-installation script returned error exit status 1
2019-09-23 15:10:25,903: DEBUG - Processing triggers for systemd (232-25+deb9u12) ...
2019-09-23 15:10:26,104: DEBUG - Errors were encountered while processing:
2019-09-23 15:10:26,104: DEBUG -  mailman
```

Je ne sais pas pourquoi tu as ces problemes de locales sur ton serveur : ce n'est pas du tout ta faute mais normalement l'installation de Yunohost gère la configuration des locales automatiquement. Est-ce que tu peux preciser comment tu as installé ton serveur (quel support physique, quelle image ou processus d'install ?) et quand environ (il y a 3 jours, 2 semaines, 6 mois, 4 ans ...)

Normalement les commandes suivantes devraient résoudre le probleme : 

```
sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen
locale-gen
[ "$(grep LC_ALL /etc/environment)" ] || echo 'LC_ALL="en_US.UTF-8"' >> /etc/environment
source /etc/environment
export LC_ALL
```

**Comment by nicolasVr** [comment]
Merci beaucoup.
Pour répondre à ta question, je suis sur un vps ovh que j'ai dû installer au début de l'année.
Les commandes que tu m'as données n'ont pas résolu tout de suite le problème mais cela a fonctionné après avoir généré les locales FR (la langue dans laquelle je voulais installer).
Donc, ça marche !
